import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Board from '../src/pages/Board'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tic tac toe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Board />
      </main>
    </div>
  )
}

export default Home
